global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: "webhook"    # make webhook the default receiver

receivers:
- name: "webhook"
  webhook_configs:
  - url: "http://localhost:9000/"   # Use localhost since network_mode: host
    send_resolved: true

- name: "dev-null"
  # silent fallback receiver
  webhook_configs: []
