#!/usr/bin/env python3
"""
Generate a static HTML page for football predictions,
styled to match the Shab00.github.io portfolio.
Reads the latest prediction snapshot CSV.
"""

import csv
import datetime
from pathlib import Path
import sys

# ---------- CONFIG ----------
SNAPSHOT_CSV = Path("snapshots/predictions_latest.csv")
OUTPUT_DIR = Path("football")
OUTPUT_FILE = OUTPUT_DIR / "index.html"

# ---------- HTML TEMPLATE ----------
PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Premier League Home‑Win Predictions</title>
  <style>
    :root {{
      --bg: #0f172a;
      --panel: #111827;
      --panel-border: #1f2937;
      --text: #e5e7eb;
      --muted: #94a3b8;
      --accent: #38bdf8;
      --accent-hover: #0ea5e9;
      --button-text: #082f49;
      --shadow: 0 20px 40px rgba(0, 0, 0, 0.25);
    }}
    * {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      font-family: Arial, Helvetica, sans-serif;
      background: radial-gradient(circle at top, rgba(56,189,248,0.12), transparent 30%),
                  linear-gradient(180deg, #020617 0%, #0f172a 100%);
      color: var(--text);
      min-height: 100vh;
      padding: 2rem 0;
    }}
    .container {{
      width: min(960px, calc(100% - 2rem));
      margin: 0 auto;
    }}
    h1 {{
      font-size: clamp(2rem, 4vw, 3rem);
      margin-bottom: 0.5rem;
    }}
    .updated {{
      color: var(--muted);
      font-size: 0.95rem;
      margin-bottom: 2rem;
    }}
    .predictions-table {{
      width: 100%;
      border-collapse: collapse;
      background: rgba(17,24,39,0.9);
      border: 1px solid var(--panel-border);
      border-radius: 16px;
      overflow: hidden;
      box-shadow: var(--shadow);
    }}
    th, td {{
      padding: 0.9rem 1.2rem;
      text-align: left;
      border-bottom: 1px solid var(--panel-border);
    }}
    th {{
      background: #0f172a;
      font-weight: 700;
      color: var(--accent);
      text-transform: uppercase;
      letter-spacing: 0.05em;
      font-size: 0.85rem;
    }}
    td {{
      color: var(--text);
    }}
    .prob-high {{
      color: #4ade80;
      font-weight: 700;
    }}
    .prob-mid {{
      color: #facc15;
      font-weight: 600;
    }}
    .prob-low {{
      color: #f87171;
    }}
    .footer {{
      margin-top: 2rem;
      color: var(--muted);
      font-size: 0.9rem;
      text-align: center;
    }}
    a {{
      color: var(--accent);
      text-decoration: none;
    }}
    a:hover {{
      text-decoration: underline;
    }}
  </style>
</head>
<body>
  <div class="container">
    <h1>⚽ Premier League Home‑Win Predictions</h1>
    <p class="updated">Last updated: {last_updated}</p>
    <table class="predictions-table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Home</th>
          <th>Away</th>
          <th>P(Home Win)</th>
          <th>Best Home Odds</th>
        </tr>
      </thead>
      <tbody>
        {rows}
      </tbody>
    </table>
    <div class="footer">
      <p>Generated by an automated ML pipeline. <a href="https://github.com/Shab00">View source</a></p>
    </div>
  </div>
</body>
</html>
"""

ROW_HTML = """<tr>
  <td>{date}</td>
  <td>{home}</td>
  <td>{away}</td>
  <td class="{prob_class}">{prob:.2%}</td>
  <td>{odds}</td>
</tr>"""

def generate_page(snapshot_path: Path, output_path: Path) -> None:
    if not snapshot_path.exists():
        print(f"Snapshot file not found: {snapshot_path}")
        sys.exit(1)

    rows_data = []
    with open(snapshot_path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for row in reader:
            date = row.get("kickoff_time_utc", "")[:10]
            home = row.get("home_team", "")
            away = row.get("away_team", "")
            prob_str = row.get("prob_homewin", "0")
            try:
                prob = float(prob_str)
            except (ValueError, TypeError):
                prob = 0.0
            odds = row.get("odds_B365H", "")
            if prob >= 0.6:
                prob_class = "prob-high"
            elif prob >= 0.35:
                prob_class = "prob-mid"
            else:
                prob_class = "prob-low"
            rows_data.append((date, home, away, prob, odds, prob_class))

    rows_data.sort(key=lambda x: x[0])

    html_rows = "\n".join(
        ROW_HTML.format(
            date=date,
            home=home,
            away=away,
            prob=prob,
            prob_class=prob_class,
            odds=odds if odds else "N/A"
        ) for (date, home, away, prob, odds, prob_class) in rows_data
    )

    last_updated = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    html = PAGE_TEMPLATE.format(last_updated=last_updated, rows=html_rows)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding='utf-8')
    print(f"Page generated: {output_path}")

if __name__ == "__main__":
    snapshot = Path(sys.argv[1]) if len(sys.argv) > 1 else SNAPSHOT_CSV
    output = Path(sys.argv[2]) if len(sys.argv) > 2 else OUTPUT_FILE
    generate_page(snapshot, output)
